version: "3"

networks:
    db:

services:
    postgres:
        container_name: postgres
        hostname: postgres
        restart: always
        image: postgres:latest
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - db
        environment:
            - POSTGRESQL_DATABASE=postgresdb
            - POSTGRESQL_ADMIN_PASSWORD=postgresrootpassword
            - POSTGRESQL_USER=postgresuser
            - POSTGRESQL_PASSWORD=mysecretpassword
        logging:
            options:
                max-size: "100m"
                max-file: "5"

    wirecloud:
        container_name: wirecloud
        hostname: wirecloud
        restart: always
        image: flopez/wirecloud:1.1
        ports:
            - 8000:8000
        volumes:
            - ./wirecloud_instance:/opt/wirecloud_instance
            - ./static:/var/www/static
        depends_on:
            - postgres
        networks:
            - db
        environment:
            - POSTGRES_DATABASE=postgresdb
            - POSTGRES_HOSTNAME=127.0.0.1
            - POSTGRES_USER=postgresuser
            - POSTGRES_PASSWORD=mysecretpassword
        logging:
            options:
                max-size: "100m"
                max-file: "5"
