apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wirecloud-claim2
  name: wirecloud-claim2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
